export class Game {
      gameId:string;
      gameUrl:string;
      seasonId:string;
      date:string;
      time:string;
      arena:string;
      city:string;
      state:string;
      country:string;
      homeStartDate:string;
      homeStartTime:string;
      visitorStartDate:string;
      visitorStartTime:string;
      previewAvailable:string;
      recapAvailable:string;
      notebookAvailable:string;
      tntOt:string;
      matchDescription:string;
}